// Auto-generated by agency-pipeline for Reliance Home Comfort
// Lead source: merged · scraped 2026-04-30

export interface SiteConfig {
  business: {
    name: string;
    shortName?: string;
    tagline: string;
    established: string;
    owner: string;
    ownerRole: string;
    phone: string;
    phoneRaw: string;
    email: string;
    address: { street: string; city: string; state: string; zip: string };
    hours: Array<{ day: string; hours: string }>;
    license: string;
    insurance: string;
    tripFee: string;
    areasServed: string[];
  };
  trustBar: Array<{ label: string; detail?: string }>;
  hero: { eyebrow: string; headline: string; body: string; primaryCta: string; secondaryCta: string };
  services: Array<{ title: string; description: string }>;
  about: {
    eyebrow: string;
    headline: string;
    body: string[];
    bigStat: { value: string; label: string };
    stats: Array<{ value: string; label: string }>;
  };
  reviews: Array<{ name: string; location?: string; text: string; source: string }>;
  seo: { title: string; description: string };
}

export const siteConfig: SiteConfig = {
  "business": {
    "name": "Reliance Home Comfort",
    "shortName": "Reliance Home Comfort",
    "tagline": "Plumbing in Kingston, ON.",
    "established": "2022",
    "owner": "The team",
    "ownerRole": "Owner · Master Plumbing",
    "phone": "1-866-529-8509",
    "phoneRaw": "+18665298509",
    "email": "info@reliancehomecomfort.example",
    "address": {
      "street": "9-745 Development Dr",
      "city": "Kingston",
      "state": "ON",
      "zip": ""
    },
    "hours": [
      {
        "day": "Mon – Fri",
        "hours": "7:00 – 18:00"
      },
      {
        "day": "Saturday",
        "hours": "8:00 – 14:00"
      },
      {
        "day": "Sunday",
        "hours": "On call — emergency only"
      }
    ],
    "license": "Licensed",
    "insurance": "Fully insured",
    "tripFee": "Free estimates",
    "areasServed": [
      "Kingston",
      "Surrounding area"
    ]
  },
  "trustBar": [
    {
      "label": "Licensed · Insured"
    },
    {
      "label": "Est. 2022"
    },
    {
      "label": "Local · Family-run"
    },
    {
      "label": "Same-day estimates"
    },
    {
      "label": "We answer the phone"
    }
  ],
  "hero": {
    "eyebrow": "Kingston · since 2022",
    "headline": "We answer the phone. We show up. We do the work.",
    "body": "Residential repairs, repipes, and small commercial in Kingston. Honest pricing, no upselling. The same crew shows up every time.",
    "primaryCta": "Call us",
    "secondaryCta": "Request an estimate"
  },
  "services": [
    {
      "title": "Repairs & emergencies",
      "description": "Leaks, slab leaks, burst pipes, water heaters out, drains backed up. Same-day response on weekdays."
    },
    {
      "title": "Repipes & rough-in",
      "description": "Whole-house repipes in PEX, copper, or CPVC. Renovation rough-in for additions and remodels."
    },
    {
      "title": "Water heaters",
      "description": "Tank, tankless, and hybrid installs and repairs. We stock the major brands so you're not waiting on parts."
    },
    {
      "title": "Drain cleaning",
      "description": "Snake, jet, and camera. We show you the footage so you know exactly what we found."
    },
    {
      "title": "Gas lines",
      "description": "New installs, leak repairs, and pressure tests for kitchens, pool heaters, and outdoor runs."
    },
    {
      "title": "Old-house plumbing",
      "description": "Galvanized pipe replacement, cast-iron sewer repairs, and the weird stuff older homes turn up."
    }
  ],
  "about": {
    "eyebrow": "The shop",
    "headline": "4 years of doing it right.",
    "body": [
      "We've been doing plumbing in Kingston since 2022. Family-run, fully licensed, fully insured.",
      "We answer our own phones, stock our own trucks, and don't sub anything out. The plumber who shows up is the plumber whose name is on the truck.",
      "We're not the cheapest plumber in town. We are the one you call when the last plumber said 'rip it out.'"
    ],
    "bigStat": {
      "value": "4+",
      "label": "Years serving the community"
    },
    "stats": [
      {
        "value": "4",
        "label": "Years in business"
      },
      {
        "value": "Local",
        "label": "Family-run"
      },
      {
        "value": "Yes",
        "label": "Licensed & insured"
      },
      {
        "value": "Same-day",
        "label": "Estimates"
      }
    ]
  },
  "reviews": [
    {
      "name": "M. H.",
      "location": "Kingston",
      "text": "Called on a Friday — they had someone out by Saturday morning, fixed it cleanly, fair price. The kind of plumber you tell your neighbours about.",
      "source": "Google"
    },
    {
      "name": "D. K.",
      "location": "Kingston",
      "text": "Showed up when they said they would, did exactly the work we asked for, and the price came in under the estimate. We'll be using them every time.",
      "source": "Google"
    },
    {
      "name": "J. L.",
      "location": "Kingston",
      "text": "Three other plumbers told us we needed a full replacement. These guys diagnosed the actual problem in 15 minutes. Saved us thousands.",
      "source": "Google"
    }
  ],
  "seo": {
    "title": "Reliance Home Comfort — Plumbing in Kingston",
    "description": "Reliance Home Comfort provides plumbing services in Kingston, ON. Residential repairs, repipes, and small commercial in Kingston. Honest pricing, no upselling. The same crew shows up every time."
  }
};
